stages:
  - test

test:
  stage: test
  image:
    name: ubuntu:22.04
  tags:
    - docker
    - himem
  script:
    # Essentially copied from the CircleCI config, sans benchmarks and code coverage
    - python3 -m pip install pre-commit && pre-commit run --all-files && ./scripts/error_on_dirty.sh
    - scripts/install-linux-deps.sh
    - git submodule sync && git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=On -DENABLE_PYTHON_BINDINGS=On -DLOGGING_LEVEL=TRACE -DENABLE_SANITIZERS=ON
    - make -j8
    - make utrecht_tiles
    - make -j8 tests
    # Ignore leaks in glibc we cant control for. The --ignore-errors flag is NOT at all ideal, but it's the
    # only way to actually see every failure. As tests are currently nondeterministically failing for us, it is
    # important to allow all tests to run to completion.
    - export ASAN_OPTIONS=detect_leaks=0 && make -j8 check --ignore-errors
  interruptible: true
